### ISSUE TITLE
Raise a Shield loops on a token

### ISSUE THREAD

**Issue by ByronThompson** [MrVauxs/pf2e-jb2a-macros#10]
The included Autorec settings include setting for Raise a Shield which calls the Raise a shield macro. If the Raise a Shield effect is placed on a token, the macro is called, which removes the effect from the token, which will call the macro and replace the effect on the token, and so on, until the token is deleted.

**Comment by MrVauxs** [comment]
Please update to the most recent version of the Autorecognition File, as this is not present in the current version.

There should be two Raise a Shield effects in the Autorecognition menu, one for the action which causes the macro, and one for the active effect, which plays the animation.
