### ISSUE TITLE
Scatter Scree

### ISSUE THREAD

**Issue by MrVauxs** [MrVauxs/pf2e-jb2a-macros#105]
my mortal enemy

**Comment by rarick** [comment]
Hey there, I came across this bug myself as well :smiley: Any idea what the root cause is?

I could take a look as well - if you have any advice I'd appreciate it!

**Comment by MrVauxs** [comment]
There is no bug, there is simply no good way to animate it as far as I've seen,

**Comment by rarick** [comment]
Oh, I gotcha. Before I started using this plugin, I had one set in `automated-jb2a-animations` - I  mistook it for one from this plugin.

I had tried using `jb2a.falling_rocks`, as it was the closest I could find that was "rock/earth" thematic. But `automated-jb2a-animations` didn't seem capable of playing it.

Amazing plugin by the way!
