### ISSUE TITLE
Change shape and token images with overhang (bestiary pack)

### ISSUE THREAD

**Issue by Far2Casual** [MrVauxs/pf2e-jb2a-macros#106]
Trying to allow my Druid to use the tokens provided by the premium token pack, there's a slight limitation when using some of the tokens with massive amounts of overhang. Here my level 13 Druid transforming into a Gigantic Brontosaurus.

https://user-images.githubusercontent.com/63196064/216775744-7b2b9377-0f13-49ba-9f37-7e041157b930.mp4

**Comment by MrVauxs** [comment]
Something else is changing your token image and scale, most likely a rule element you made, as shown by the token being changed before the animation even starts.

https://user-images.githubusercontent.com/32039708/216776863-9b001e2c-877d-4980-9e53-587b2179e28c.mp4
![image](https://user-images.githubusercontent.com/32039708/216776871-18955ee6-aaba-44bd-9d52-cdec28336109.png)

**Comment by MrVauxs** [comment]
There's also certainly something overriding the mutation from PF2e Animations given that the token is then snapped back to the original `1.0` scale.

**Comment by Far2Casual** [comment]
Right, I have removed the custom RE I used to use to change the token image. But the end result is the same.

https://user-images.githubusercontent.com/63196064/216780579-602b2216-1269-4756-a5f4-a250f4517c8f.mp4

**Comment by Far2Casual** [comment]
If I go on the token and "unlock" the Scale option (in the appearance tab), then it takes the appropriate size.

**Comment by MrVauxs** [comment]
You can disable the PF2e system's "Scale according to size" setting and that should help.
Otherwise I can't fix this without rewriting to use rule elements.

**Comment by Far2Casual** [comment]
Sure, I understand. Thanks for the lightning fast answer, the help, and the generally awesome module !
