### ISSUE TITLE
Sudden Charge issues

### ISSUE THREAD

**Issue by jocolamarco** [MrVauxs/pf2e-jb2a-macros#111]
Versions:
- fvtt 10.291
- pf2e 4.7.2
- pf2e animations 2.10.4

Issues:
1. _[minor issue]_ ft distance calculation isn't accurate and shows diferent values sometimes (eg 5ft and then 10ft in the exact same square)
2. When teleporting the token, it's not moved to the selected square

Please see the attached video for both:

[sudden charge animation.webm](https://user-images.githubusercontent.com/45291719/217856043-1f01b919-71af-4cbd-be4d-daf50de0fda5.webm)

DEBUG:
![image](https://user-images.githubusercontent.com/45291719/217855351-311dba23-bb58-4adb-824e-97ba5ed77255.png)

![image](https://user-images.githubusercontent.com/45291719/217855487-62301133-8d86-41c0-a214-262f6d402119.png)

**Comment by MrVauxs** [comment]
Check out [2.10.5](https://github.com/MrVauxs/pf2e-jb2a-macros/releases/tag/2.10.5) if it fixes anything.

**Comment by jocolamarco** [comment]
It's still going to a square nearby the crosshairs target, do you see anything weird on my grid settings that would explain this?

![image](https://user-images.githubusercontent.com/45291719/218417840-76e3a481-9759-404f-8dc0-93a8011a4aba.png)


I'll do some more tests later in a bunch of different scenes
