### ISSUE TITLE
Bow attacks cause user facing error if soundfx not installed

### ISSUE THREAD

**Issue by mothringer** [MrVauxs/pf2e-jb2a-macros#119]
Bow attacks are causing an error to be presented to the user making the attacks if the module is used without soundfxlibrary installed, instead of the console-only error for other missing sound effects. The error appears to be presented by sequencer, so not sure if the bug is with this module's mapping or something in sequencer.

**Comment by MrVauxs** [comment]
What error is being shown?

**Comment by mothringer** [comment]
Sequencer | getFiles | Directory modules/soundfxlibrary/Combat/Single/Arrow Fly-By does not exist or is not accessible in this storage location

Sequencer | getFiles | Directory modules/soundfxlibrary/Combat/Single/Arrow Impact does not exist or is not accessible in this storage location
