### ISSUE TITLE
[Spell Request] Healer's Blessing

### ISSUE THREAD

**Issue by BasiliskOnline** [MrVauxs/pf2e-jb2a-macros#123]
By default Healer's Blessing triggers "Bless" which is not appropriate, currently I have set bless to force Exact match to prevent that (statement here in case other people are here and search Healer's Blessing in the meantime).

Would love this spell to be added to the default list as soon as you have the time available. <3

**Comment by MrVauxs** [comment]
Added in [2.11.0](https://github.com/MrVauxs/pf2e-jb2a-macros/releases/tag/2.11.0)
