### ISSUE TITLE
"Concealed" macro generating errors and not changing visual effects

### ISSUE THREAD

**Issue by humer-me** [MrVauxs/pf2e-jb2a-macros#126]
Running the "Concealed" macro (either by applying the condition to a token or running the macro itself) does not change token visual effects and generates two macro errors:

`TypeError: wrapped is not a function`

`ReferenceError: TokenMagic is not defined`

![image](https://user-images.githubusercontent.com/1291073/224604152-90b22bf6-242c-440f-ace8-70f2ac28f85f.png)

**Relevant Modules Installed and Enabled**
Advanced Macros 1.19.5
Automated Animations 4.2.32
Full JB2A Patreon module 0.5.4
PF2e Animations 2.10.9
Warpgate 1.16.2

Foundry v10.291
PF2e v4.9.1

**Comment by MrVauxs** [comment]
You have likely enabled TokenMagicFX at some point, then disabled it.
Enable TMFX and use the TMFX version of the macro, or enable TMFX and disable the setting to use TMFX animations in PF2e Animations settings.
