### ISSUE TITLE
Feature Request: Update Add Effect Macro to increase the counter on an effect

### ISSUE THREAD

**Issue by blacktrench** [MrVauxs/pf2e-jb2a-macros#127]
Hey!

Is there a way to make Compendium.pf2e-jb2a-macros.Macros.Add Effect increase the counter on an effect after adding the initial effect instead of adding another stack of the effect? For example, I have daemonic pestilence setup to add an effect for the disease that has a counter on it for each stage of the disease, if I use the action it is tied to again it would increase the counter by 1 instead of add another stack/effect for daemonic pestilence.

Thanks!

**Comment by MrVauxs** [comment]
Added in next release.
