### ISSUE TITLE
Add Effect macro not finding system badge

### ISSUE THREAD

**Issue by this-gavagai** [MrVauxs/pf2e-jb2a-macros#129]
First, thanks for this awesome module. You've made some great design choices, and they've improved my table's game tremendously.

On latest versions, I've noticed an issue with a few applications of the `Add Effect` macro. Specifically, the Inspire Courage spell isn't working for me anymore, with the following error in console:

```
12378:22 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'system')
[Detected 2 packages: advanced-macros, sequencer]
    at add (eval at executeScript (lib.js:175:13), <anonymous>:22:12)
    at ask (eval at executeScript (lib.js:175:13), <anonymous>:31:3)
    at eval (eval at executeScript (lib.js:175:13), <anonymous>:74:7)
    at async Macro.executeMacro (lib.js:77:9)
    at async Proxy.<anonymous> (sequencer.js:127:9)
    at async Proxy.run (func.js:18:5)
    at async Proxy._execute (func.js:26:5)
    at async Proxy.play (sequencer.js:42:23)
```

I don't understand the system well enough yet to understand the problem, but it's related to the code here in the Add Effect macro, where the `find` argument is coming back undefined.
```javascript
async function ask(source, deleteTemplate) {

	async function add() {
		const find = args[1].sourceToken.actor.items.find(x => x?.flags?.core?.sourceId === source.flags.core.sourceId)
		if (find.system.badge) {
			find.update({"system.badge.value": find.system.badge.value += 1})
		} else {
			await args[1].sourceToken.actor.createEmbeddedDocuments("Item", [source]);
		}
		if (deleteTemplate && args[0].documentName === "MeasuredTemplate") args[0].delete();
	}
```
I was able to fix the issue in my case by changing the subsequent `find.system.badge` call to use optional chaining: `find?.system?.badge`.

This feels like a lousy fix on my end, and I wish I understood the system to be able to troubleshoot better, but I thought I'd share. Let me know if I can help debug in anyway.

**Comment by MrVauxs** [comment]
Fixed in the next update.
