### ISSUE TITLE
Dragon Form size increase

### ISSUE THREAD

**Issue by zagaroth** [MrVauxs/pf2e-jb2a-macros#132]
PF2E Animations has a size-increase effect upon applying the effects of Dragon Form. 

However, Dragon Form currently has a size-adjusting effect built into it. This causes the character's size to be adjusted first by the Dragon Form effect, and then to increase again when the Animation goes off, turning a Large character into a Huge character. 

As size change is being handled by the spell effect, there is no longer a need for it to be handled by this mod.

**Comment by MrVauxs** [comment]
PF2e Animations does not change the size of the token, nor can I replicate any such issue.

https://user-images.githubusercontent.com/32039708/235350263-de810b59-f03c-462a-8d16-1e7b22e6fc51.mp4

**Comment by zagaroth** [comment]
Hmmm, shoot, maybe it was automatic animations then, Foundry said PF2E Animations was dependent upon it so I simply turned off both at the same time. Bah, that's what I get for trying to troubleshoot it late at night after we'd just had a long game, I didn't think that through and should have double-checked. I'm sorry.

**Comment by zagaroth** [comment]
Oh, and there was an update that apparently released during the game, so there is a chance it was fixed with that.

**Comment by MrVauxs** [comment]
Please make sure you are on the latest version of PF2e Animations and list the version. Green Dragon Form works as well.

**Comment by zagaroth** [comment]
Version: 2.12.5
I believe during game we were on the previous version. I run updates at least once a week.


https://user-images.githubusercontent.com/9573333/235376228-e6aaabd5-e807-4488-afa5-ad1845f3252c.mp4

**Comment by MrVauxs** [comment]
I genuinely cannot replicate this. Have you ran the update menu in PF2e Animations settings?

**Comment by zagaroth** [comment]
Just ran that, only thing it wanted to update was Aeon stones. No change. I'm poking at some other modules now to see if I can find something else interfering.

**Comment by zagaroth** [comment]
Okay, I am not sure what to do here. I created a new world, and only activated the modules that Foundry told me I had to activate for PF2E Animations, and then the modules that *those* modules required. I got the same results. 

<img width="535" alt="image" src="https://user-images.githubusercontent.com/9573333/235391692-7c512268-e743-4d96-9413-65c72728afc6.png">


https://user-images.githubusercontent.com/9573333/235391729-d1a3bb0c-7f40-444a-8845-6aebc46f451d.mp4

I've run 'update all' on both the system and the modules.

**Comment by zagaroth** [comment]
And I hadn't tried their paid package before, and I read that your set up is oriented toward the JB2A Patreon package, so I have tried that now with the same results. 

Tested with both free and Patreon active, and only Patreon active

<img width="558" alt="image" src="https://user-images.githubusercontent.com/9573333/235412910-6b4b94f9-6d6a-43ac-a79d-2df648b3e8ed.png">

**Comment by MrVauxs** [comment]
You have outdated Advanced Macros.

**Comment by zagaroth** [comment]
Huh. That one has not been updating via 'update all' then. 

hmm, I just manually went to the URL, it says its latest release was 1.19.6 on March 16, which is what I have.

https://github.com/mclemente/fvtt-advanced-macros

**Comment by MrVauxs** [comment]
I have found the issue. With the lack of Bestiary Packs, you don't get the image but you still get the scale increase.
It's not the size being increased, but the scale. The token still is 1 by 1.

Will be fixed in the next update.
