### ISSUE TITLE
Localization support for automatic recognization

### ISSUE THREAD

**Issue by slowcar** [MrVauxs/pf2e-jb2a-macros#134]
I am using Pathfinder2e in German and would like to use automated animations.
It looks like the detection is based on strings that are localized in foundry, for example "magic missile" is "magisches geschoss" in the character sheet.

Looking at autorec.json there does not seem to be localization support for the label, maybe it would be possible to add that?

I can duplicate entries and add the German name, at least for the items and spells we actually use, but if the module would support localization for the detection I and others could provide the translation inline.

**Comment by MrVauxs** [comment]
Automated Animations should already work with localizations such as Babele. 
If your animations don't work in the German version, report is as a bug in Automated Animations GitHub Repo.
