### ISSUE TITLE
Syntax issue in Mirror Image

### ISSUE THREAD

**Issue by crewsermiester** [MrVauxs/pf2e-jb2a-macros#140]
I am running v10 foundry PF2e. I am running PF2e animations with the JB2a full pack. I think there is supposed to be a visual effect for mirror image but it just always throws these two errors when I cast. "advanced-macros SyntaError: Unexpexted token ')'" and "there was an error in your macro syntax. see the console(F12) for details"

**Comment by crewsermiester** [comment]
Additionally i did some more digging and it looks like the syntax error may be an extra paranthises in line 47

**Comment by MrVauxs** [comment]
Please make sure you are on the latest version of PF2e Animations and are not using your own version of the macro.
The macro works as it is.

https://github.com/MrVauxs/pf2e-jb2a-macros/assets/32039708/76b55e9c-b4a9-4baa-8df4-286526ebeec6
