### ISSUE TITLE
Translated System

### ISSUE THREAD

**Issue by uLotUu** [MrVauxs/pf2e-jb2a-macros#141]
When translating system to another language automated animations does not recognize names. It's easy to change animation for a skill or a spell but not with system-wide names. For example - everytime a character get's damage from persistant damage I get an error "cannot find ogień (polish for fire)". It would be nice to be able to be able to translate those names for people using other languages

**Comment by MrVauxs** [comment]
No longer in the module. May make a comeback eventually.
