### ISSUE TITLE
JB2A module dependency (vs. S3 storage)

### ISSUE THREAD

**Issue by this-gavagai** [MrVauxs/pf2e-jb2a-macros#142]
Hello,

First off, thanks for this fantastic module. Not only is it a huge convenience to have so many of these spells and effects come predefined, you've really shown what's possible in a way that I wouldn't have ever figured out on my own!

I have a question about an error I'm getting on load: When I start, my game trips this error message:
https://github.com/MrVauxs/pf2e-jb2a-macros/blob/7ab57c8b942b6cee3fde1925736378414effe1c8/module/pf2e-animations.js#L9-L10

I have JB2A animations installed, but not as a module. Instead, it's set up as an S3 directory defined in the Automated Animations settings. Everything seems to work fine, but I'm wondering if there are other ways that pf2e-jb2a-macros is expecting the module rather than just the folder. Is setting this up this way valid, or is the error correct that we need the module specifically?

Thanks again!

**Comment by MrVauxs** [comment]
You still need to have the module enabled to include it's databases, you can simply store the modules actual artwork on S3.

**Comment by this-gavagai** [comment]
Ah, okay. I was trying to avoid downloading the massive patreon module and having to store it. Is there any way to use this module without storing jb2a-patreon and all it's massive video files locally?

**Comment by MrVauxs** [comment]
As i said, put the artwork AND ONLY the artwork in the S3 bucket.

Just leave the rest of the module in Foundry.

**Comment by this-gavagai** [comment]
Thank you, yes, that's what I've done. I've got the artwork and only the artwork in the S3 bucket. My question was about how to avoid having to download all the very large files *also* to the local module folder. I'm not aware of any way to download the module without also downloading the large files contained within it. I understand you to be saying that's not possible.

Thanks again!

**Comment by MrVauxs** [comment]
Download the module on another device and delete the artwork there. Upload the modified module to the server.
