### ISSUE TITLE
Errors seen when adding/removing concealed if Token Magic FX not enabled

### ISSUE THREAD

**Issue by olilan1** [MrVauxs/pf2e-jb2a-macros#146]
If Token Magic FX is not enabled, then when adding or removing the Concealed condition from a token error messages appear saying:

`foundry.js:59187 advanced-macros | TypeError: wrapped is not a function`

`There was an error in your macro syntax. See the console (F12) for details.`

`foundry.js:59187 advanced-macros | There was an error in your macro syntax. See the console (F12) for details : ReferenceError: TokenMagic is not defined`

PF2e Animations 2.13.1

**Comment by MrVauxs** [comment]
Pretty sure this has been fixed on latest version. Closing.
