### ISSUE TITLE
Animal Instinct Rule Element support

### ISSUE THREAD

**Issue by Ghilteras** [MrVauxs/pf2e-jb2a-macros#15]
Looks like Barbarian Animal Instinct animation (Unarmed Attack) is not working anymore since the last update? Before I could just clone Unarmed Attack and bind it to the Rule Element name (i.e. Animal Instinct)

**Comment by Ghilteras** [comment]
might be because of this https://github.com/otigon/automated-jb2a-animations/pull/437

**Comment by MrVauxs** [comment]
It is indeed because of AA. Not my module.

**Comment by Ghilteras** [comment]
Thanks @MrVauxs sorry for the noise
