### ISSUE TITLE
Token Opacity is set to 0 when Monk activates Stumbling stance

### ISSUE THREAD

**Issue by mPAQ** [MrVauxs/pf2e-jb2a-macros#150]
pf2e campaign, activating stumbling stance is setting the opacity of the token to 0

**Comment by MrVauxs** [comment]
It's a known Sequencer error that I cannot fix. You can however enable Token Magic FX animations, which will avoid this issue entirely.

**Comment by mPAQ** [comment]
Thanks, that did the trick. Little tricky to figure out how to get it to
work but it's working now, appreciate the quick response and the great
module!

**Comment by teknovus** [comment]
I was able to workaround this problem by making a copy of the macro called by A-A, and changing the .opacity field from 0 to 1 in that macro
