### ISSUE TITLE
Dancing Lights macro doesn't work

### ISSUE THREAD

**Issue by LonePaladin** [MrVauxs/pf2e-jb2a-macros#151]
The animation macro for the Dancing Lights spell doesn't work. The summoning pop-up is locked to four entities, but the spell says "up to four". When you select a color and click on the summon button at the bottom, the window minimizes and you get a placement selector showing a semi-transparent light at the cursor -- but when you click on a location, all you get is a 1-square-diameter blank template. No animation, no token, no light, just a blank space. The "Pick a Creature" window remains even after this. I've tried reopening it and picking more lights and locations, thinking maybe it wants four of them, but it never places anything but blank templates and the window doesn't go away on its own. I tried editing the macro to unlock the quantity and changing it to 1, but that didn't change its behavior.

**Comment by MrVauxs** [comment]
Open the console and see the errors. Something is going wrong when trying to summon.

**Comment by LonePaladin** [comment]
Looks like this might partly be an issue with [Foundry Summons](https://github.com/MrVauxs/foundry-summons). The macro starts with a comment that says that module is required.

**Comment by MrVauxs** [comment]
Please make sure you are up to date on both modules. And use the spell, not the macro.

**Comment by LonePaladin** [comment]
I did. Everything's updated, and I tried both the spell and the macro.

This is what I get instead of an animation leading to a light-emitting token:
![image](https://github.com/MrVauxs/pf2e-jb2a-macros/assets/37523352/2e4b9b09-91ab-4a3a-8d5e-e8b031de2b60)

Screenshots showing version numbers:
![image](https://github.com/MrVauxs/pf2e-jb2a-macros/assets/37523352/376596dc-83cb-4752-bd98-d69ff8b273bc)
![image](https://github.com/MrVauxs/pf2e-jb2a-macros/assets/37523352/f94d1389-77c6-4607-b9d4-86190e4043b6)
![image](https://github.com/MrVauxs/pf2e-jb2a-macros/assets/37523352/a0978994-d380-463c-96eb-312c1a49fad2)
![image](https://github.com/MrVauxs/pf2e-jb2a-macros/assets/37523352/fa80231d-e4ca-4790-8dfa-597349c92d26)

**Comment by MrVauxs** [comment]
You are **4 versions out of date** on PF2e Animations. 
![image](https://github.com/MrVauxs/pf2e-jb2a-macros/assets/32039708/71402516-4095-4155-9a79-07ee7657849b)
![image](https://github.com/MrVauxs/pf2e-jb2a-macros/assets/32039708/02efbfb3-fff4-4c5e-ba2f-3ab62ddcb837)
