### ISSUE TITLE
Condition Animations spawn in the upper left after swtiching scenes 

### ISSUE THREAD

**Issue by aburley1234** [MrVauxs/pf2e-jb2a-macros#152]
Seeing a bug I think with PF2e Animations though it might be with Sequencer. After loading into a scene with a creature with a condition, such as the slowed condition, loading into another scene, and then coming back to the original scene, the animations get sent to the upper lefthand corner. I don't see any errors in the log, all my stuff is on the latest 

FVTT: 11.305
PF2e: 5.1.1 
Sequencer: 3.1.0
PF2e Animations: 2.15.5
Automated Animations: 4.2.60
Warp Gate: 1.17.2 

![Screenshot 2023-07-07 201159](https://github.com/MrVauxs/pf2e-jb2a-macros/assets/1166210/6da2a41b-8d7b-4db9-85b9-85e03ff4d3f7)
![Screenshot 2023-07-07 201213](https://github.com/MrVauxs/pf2e-jb2a-macros/assets/1166210/b8927797-5559-4a00-b53a-fdaeee00f7c9)

**Comment by MrVauxs** [comment]
It is indeed a Sequencer bug.

**Comment by Haxxer** [comment]
Could someone provide the macro that causes this? I can't seem to reproduce the issue.
