### ISSUE TITLE
Summoning Incompatible with v10 Build 291

### ISSUE THREAD

**Issue by relaytheory** [MrVauxs/pf2e-jb2a-macros#154]
Attempting to summon using a spell such as "Summon Lesser Servitor" with the automated macro results in a partial loss of canvas functionality and ghost tokens.

Module List includes:
Advanced Macros
Automated Animations
JB2A - Patreon Complete Collection
libWrapper
PF2e Animations
Sequencer
socketlib
Warp Gate

![Screenshot_3](https://github.com/MrVauxs/pf2e-jb2a-macros/assets/32248765/c15ced1e-1ea7-4db6-8f77-d27a26cdbcbf)

**Comment by MrVauxs** [comment]
This looks like a Warpgate error for what it's worth, but in either case V10 is no longer supported.
