### ISSUE TITLE
Summons no longer work. 

### ISSUE THREAD

**Issue by cordwartman** [MrVauxs/pf2e-jb2a-macros#158]
Summons stopped working after latest update.
Constantly receive "PF2e Animations | Foundry Summons is not activated, which is required for summoning mechanics!" in the console but there is no option in the mod settings to "activate" Foundry Summons.

**Comment by MrVauxs** [comment]
Because that is a [module](https://foundryvtt.com/packages/foundry-summons) you are now required to install in order to summon.
