### ISSUE TITLE
Ability "Energy Beam" plays no FX

### ISSUE THREAD

**Issue by Ironxxx** [MrVauxs/pf2e-jb2a-macros#16]
Prior to version 1.9.2 I had an ability named Energy Beam (from the Automaton racial) which worked as a Ranged targeted ability.

I updated to 1.9.2 and this stopped working. No FX or SFX played at all and no errors come up in the console. I originally merged the Autorec when I updated to 1.9.2. I have since deleted Energy Beam and tried setting it up again and it still doesn't work. I have set it up as on "On target" ability, that doesn't work either. 

I have another ability, Scatter Scree (which works on a template), which was also present pre-1.9.2, which has continued to work, so I am completely stumped at this point. 

Thanks for a great mod.

**Comment by MrVauxs** [comment]
Ability given Unarmed Strikes do not work with AA, only "Unarmed Strike" works.

As for Scatter Scree, I can't say anything. 1.9.2 does nothing to change that. Your issues are likely due to AA updates.
