### ISSUE TITLE
Can't end Aeon Stone effect?

### ISSUE THREAD

**Issue by Ryminer2** [MrVauxs/pf2e-jb2a-macros#164]
Pretty much what the title says. I activated the Aeon Stone macro because I use Aeon Stones in my game, and it worked perfectly...for RAW stones. I use a lot of _homebrew_ stones in my game, so I wanted  to try adding them to the macro, but executing it again doesn't seem to update the effect to include my additions, and as far as I can tell this macro doesn't use a Hook, so I can't end it manually nor does it end automatically when I close and reopen Foundry. As it stands over half of the Aeon Stones my players have don't display correctly, so any input on what I can do about this would be great

**Comment by MrVauxs** [comment]
To end an animation, go to [Sequencer Effect Manager](https://fantasycomputer.works/FoundryVTT-Sequencer/#/effect-manager?id=show-effect-manager) and remove the animation there.

Other than that, the macro as you said is only built for the stones already in the game. Homebrew is completely unaccounted for.

**Comment by Ryminer2** [comment]
Figured it out -- I did import and modify the macro as you said, but it slipped my mind that it was AA actually running the macro and thus forgot to tell it to use mine instead of the Compendium version. Thanks.
