### ISSUE TITLE
[Bug] Token vanishes with Encumbered animation and animations disabled

### ISSUE THREAD

**Issue by bogga** [MrVauxs/pf2e-jb2a-macros#167]
When a character is encumbered, the token vanishes for players who have animations disabled

**Comment by MrVauxs** [comment]
Remove the Encumbered animation from your Automated Animations menu if you have anyone who disables animations. 
Or install TMFX and the usage of TMFX in PF2e Animations, which goes around this issue by not requiring the token to be hidden and replaced with a fake Sequencer animation (which your player removes as part of disabling animations).

**Comment by bogga** [comment]
ok, thanks! As an added bit: myself and my players are huge fans of this module, everything but this small issue has been seamless
