### ISSUE TITLE
On Hit or Miss Animations getting Sequencer error since update v 1.10.1

### ISSUE THREAD

**Issue by blacktrench** [MrVauxs/pf2e-jb2a-macros#17]
get the following error when attacks hit/miss or criti hit/miss since updating to v 1.10.1 from 1.9.2

![image](https://user-images.githubusercontent.com/24504912/187151538-607a2cdc-641a-43a1-89b6-e31451392612.png)

Imported new autorec and disabled all other modules except bare bones (this module, AA, sequence and JB2a) error still occurs

reverted to your earlier release issue goes away. Hope this helps, cheers!

**Comment by MrVauxs** [comment]
I will ask, does the animation actually play on the earlier version, or simply throw another error in the console?

As it stands, this is likely an AA issue. Already reported though.

**Comment by MrVauxs** [comment]
Fixed in 1.10.2

**Comment by blacktrench** [comment]
Downloaded the update to test, no error now but still no animations are playing; I reread your prior message and I realize that I may not have been 100% clear, animations worked on 1.92. but do not work on 1.10.1 and now 1.10.2.

**Comment by MrVauxs** [comment]
... fixed in 1.10.3
