### ISSUE TITLE
[BUG] PF2E - When you attack with a Light Mace you cast the Light spell.

### ISSUE THREAD

**Issue by GusBabiski** [MrVauxs/pf2e-jb2a-macros#174]
**Module Version:** v1.7.5

**Describe the bug**
When you Strike with the weapon Light Mace the module opens the windows to summon Dancing Lights as if you had cast the Light spell.

**To Reproduce**
1. Add a Light Mace to the characters inventory
2. Go to the Actions tab
3. Click to Strike with the Light Mace

**Expected behavior**
Window to summon Dancing Lights will appears as if you had cast the Light spell

**Screenshots**
[Here's how it looks](https://imgur.com/uRjTRu9)

**Browser:**
Standalone Foundry VTT Aplication

**Foundry Version:** 11

**Game System:** Pathfinder Second Edition

**Comment by MrVauxs** [comment]
You can fix this by making the "Light" animation in Automated Animations strict. Click the three dots on the right and advanced filter options. There, you can make it have a strict word match, so only "Light" will trigger it.

Will be fixed in the next update.
