### ISSUE TITLE
Stop Auto Center Zoom with Devise a Stratagem

### ISSUE THREAD

**Issue by DoritoBob** [MrVauxs/pf2e-jb2a-macros#187]
Is there a way to stop the auto zoom and center with the text "think think think" when a character uses Devise a Stratagem?  All of the other players in my campaigns have asked me to please stop that animation, center and zoom.  I think this the module that is doing it (I used Find the Culprit to narrow it down) 

If possible, could an option be added to disable that?

**Comment by MrVauxs** [comment]
Remove the entry from Automated Animations and it'll stop

**Comment by DoritoBob** [comment]
Thank you.  I removed it, issue fixed.  One final question please, I notice when I hint preview animation, it does a cool rune like effect.  I have never seen that effect when Devise a Stratagem is used.  It there a way to make that animation only vice the zoom in center and text?

**Comment by MrVauxs** [comment]
The preview animation is a bug on the AA side and is not representative of what actually happens.

**Comment by DoritoBob** [comment]
Got it, thanks, your hard work is much appreciated..  A animation on the actual token would be cool in the future if possible.
