### ISSUE TITLE
Not compatible with v12

### ISSUE THREAD

**Issue by lancir** [MrVauxs/pf2e-jb2a-macros#189]
With Foundry v12 installed the marketplace shows that this module is "incompatible" and it can't be enabled. 

![image](https://github.com/MrVauxs/pf2e-jb2a-macros/assets/9244358/5ca2c5a5-c89d-4fe6-95ca-ed3309222103)

**Comment by MrVauxs** [comment]
Because it's not compatible with V12.

**Comment by lancir** [comment]
I'm just a bit unclear - is this module just never going to support v12 or is there a dependency that needs to be updated before this will work?  I love your module and I'd be happy to support you on Patreon if this is going to be fixed at some point, but I'd like to know if there is any hope. :)

**Comment by MrVauxs** [comment]
PF2e Animations is an add-on for Automated Animations, which is in maintenance mode and will likely take a while before it becomes available on V12, if ever.

It also has plenty of macros that depend on Warpgate, which has stopped development and is already completely broken on V12.

It is also dependent on Sequencer, which is the module that actually creates the animations under the hood. While a V12 version is being made, its not yet finished.

Overall I am planning on replacing PF2e Animations with a new module, but right now you will have to wait a long time for this one to work on V12.

**Comment by Lioheart** [comment]
Automated Animation has version 12.
