### ISSUE TITLE
Import doesn't work

### ISSUE THREAD

**Issue by HDScurox** [MrVauxs/pf2e-jb2a-macros#2]
After the import of the autorec.json into automated animations, it creats every "type" of Spell, but the settings of each spell/weapon/attack are empty :O

I'm using the Forge as a hosting service, if that helps - if I import my own backup everthing works, so I think the importer does its job.
I have the jb2a Patreon module as well.

**Comment by MrVauxs** [comment]
I have been updating the repository and along with it, the autorec, using the experimental version of Automated Animations.
That experimental version is incompatible with its previous version, as it's the Svelte update.

I have added the non-beta version of the autorec file to the latest stable release, and modified the workflow so it is included in every single one going forward.
You can find it **[here](https://github.com/MrVauxs/pf2e-jb2a-macros/releases/latest)**, and with the [direct download](https://github.com/MrVauxs/pf2e-jb2a-macros/releases/latest/download/autorec.json).
