### ISSUE TITLE
Animation play on attack roll and damage application

### ISSUE THREAD

**Issue by Zatorg** [MrVauxs/pf2e-jb2a-macros#200]
When I attack a pc with a npc and I hit the animation for the attack plays. But when I the roll the damage and apply it with the chat button, the animation plays again. When select the player token the animation even plays from the player token.

Foundry Version: V12 330
PF Module Version: 6.2.0
Automated Animations: 4.2.77
JB2A - Patreon: 0.7.0
Sequencer: 3.2.12
socketlib: 1.1.0
pf2e-jb2a-macros: 2.18.2

**Comment by MrVauxs** [comment]
Fixed by https://github.com/otigon/automated-jb2a-animations/pull/713
