### ISSUE TITLE
Encumbrance macro seems to make tokens way bigger than intended

### ISSUE THREAD

**Issue by blacktrench** [MrVauxs/pf2e-jb2a-macros#21]
Hey, I tested with multiple token whereas before it used to just make them pulse now it enlarges them quite a bit more than earlier versions.

![image](https://user-images.githubusercontent.com/24504912/189507842-a570105c-64f6-4aa1-91a7-48c644a91917.png)

![image](https://user-images.githubusercontent.com/24504912/189507857-08a9709d-7b0e-4beb-9636-862e90a7b313.png)

I performed standard TS, removed any other modules except the ones required to use your module. I am still running foundry v9.269 with pf2e v3.13.6 so I am not sure if related.

let me know if you need anything else - cheers!

**Comment by MrVauxs** [comment]
This was a bug of and was fixed by Sequencer in version [2.2.1](https://github.com/fantasycalendar/FoundryVTT-Sequencer/releases/tag/2.2.1).
