### ISSUE TITLE
Issue manually installing the module

### ISSUE THREAD

**Issue by Eleuis** [MrVauxs/pf2e-jb2a-macros#24]
Foundry: Version 9 Build 269
System: Pathfinder 2e - 9.269
Module Version: Latest [1.11.1]

Hello,

Installing the module with the wizard launches the "k is not defined error"
![image](https://user-images.githubusercontent.com/33282025/190128349-e3732d77-f089-468c-a235-ee8e5650ee8d.png)

So I decided to install the module manually. 
I created the folder with the proper name:
![image](https://user-images.githubusercontent.com/33282025/190128673-0666c973-a5b7-4507-9d64-4bda701bd6d0.png)

However, the module is not being recognized by foundry, it doesn't show in the manage modules tab
![image](https://user-images.githubusercontent.com/33282025/190129123-337696fa-80f4-4a85-9817-cc4f8768830e.png)

**Comment by MrVauxs** [comment]
You are trying to download the V10 version of the module. And have manually downloaded the V10 version of the module.

Foundry doesn't show modules above your Foundry version. Install release [1.10.6](https://github.com/MrVauxs/pf2e-jb2a-macros/releases/tag/1.10.6) which is the latest for V9.
