### ISSUE TITLE
Dancing Lights macro references wrong actor name

### ISSUE THREAD

**Issue by GimpInBlack** [MrVauxs/pf2e-jb2a-macros#25]
The Dancing Lights macro attempts to spawn an actor named "Dummy PC" but the actual actor is named Dancing Light. The macro works if I rename the imported Dancing Light actor in my world to Dummy PC.

**Comment by MrVauxs** [comment]
Fixed in [1.11.4](https://github.com/MrVauxs/pf2e-jb2a-macros/releases/tag/1.11.4)
