### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by MemelyPepeartly** [MrVauxs/pf2e-jb2a-macros#3]
Using the rage macros and electric arcing spells and damage dont play the animations. Looking back into the readme, Im not entirely certain what I need to be doing to get these macros up and working, so this issue request is to see if its possible to fill out some more info in the readme of how to properly get this module's macros setup and working.

**Comment by MrVauxs** [comment]
Will do.

To explain here though, you are required to use the auto recognition file provided in the module and add it to Automated Animations, or create your own AA entries that automatically trigger the macro in the compendia.

**Comment by MrVauxs** [comment]
Created a more comprehensive guide in the README.
