### ISSUE TITLE
Is it possible to attach animations to a trait?

### ISSUE THREAD

**Issue by Janonas** [MrVauxs/pf2e-jb2a-macros#30]
Im looking to make firearms with the Scatter trait use different sounds an animations from regular ones, is there a possible way to attach it to the trait rather than to the individual weapons, so that homebrewed and new weapons (treasure vault possibly?) with this trait wont have to be added manualy?

**Comment by MrVauxs** [comment]
No, this would require an AA implementation way outside of its scope, or me adding a macro to all firearms to check for that and play an animation that would be out of sync with AA's attack roll animation.
