### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BoTKaPyC** [MrVauxs/pf2e-jb2a-macros#37]
wallow errors when pressing "sheathe" "throw" "rest the night"
![3](https://user-images.githubusercontent.com/80960291/195346930-17ef0e57-fe99-4c5d-bf91-d8710d0267e5.png)

**Comment by MrVauxs** [comment]
Version of the module and foundry? I do not get this error on latest in any of the three circumstances.

**Comment by MrVauxs** [comment]
And Automated Animations and PF2e Animations Macros?

śr., 12 paź 2022, 17:56 użytkownik BoTKaPyC ***@***.***>
napisał:

**Comment by BoTKaPyC** [comment]
AA - 4.0.07, PF2e AM - 2.0.0

**Comment by MrVauxs** [comment]
The only last thing I can imagine is your Pathfinder 2e system being out of date, sorry.

**Comment by BoTKaPyC** [comment]
PF2e 4.2.6, FVTT 10.288

**Comment by MrVauxs** [comment]
Closing as I hope this has been fixed in the last few updates.
