### ISSUE TITLE
after latest update 2.2.0 some effects disappeared and update is unavailable

### ISSUE THREAD

**Issue by Maelorn09** [MrVauxs/pf2e-jb2a-macros#38]
Hi, When I try to use the update menu it always shows the same # of items. Also some effects disappeared from the game, we had a cool effect for the frost arquebus autorecognozed, but now it's not there.
![image](https://user-images.githubusercontent.com/114569560/197139863-1748dec3-69d8-4b23-891e-6ce268e4717d.png)
![image](https://user-images.githubusercontent.com/114569560/197140072-5f27d771-b5b1-4c44-95d7-5fe702615f6f.png)

**Comment by Maelorn09** [comment]
So I suppose the update somehow fails

**Comment by Maelorn09** [comment]
Here's what I have for custom animations in the console:
![image](https://user-images.githubusercontent.com/114569560/197142134-b6cc074a-a72f-4994-8bc9-5e2ecbff82b0.png)

**Comment by MrVauxs** [comment]
What version of Automated Animations and PF2e Animation Macros are you on

**Comment by Maelorn09** [comment]
> What version of Automated Animations and PF2e Animation Macros are you on

AA - 4.0.12
PF2e AM - 2.2.0

Complete module deinstallation and reinstallation didn't help

**Comment by MrVauxs** [comment]
If you can export your current autorec menu that is causing this issue it'd be appreciated. Otherwise I am not sure how I can help.

**Comment by MrVauxs** [comment]
Also note that PF2e Animation Macros does not touch custom animations on items. If you lost that one, it was because the item was replaced or you updated to AA version 4, which had to override these with the new system.

**Comment by Maelorn09** [comment]
> Also note that PF2e Animation Macros does not touch custom animations on items. If you lost that one, it was because the item was replaced or you updated to AA version 4, which had to override these with the new system.

No, we had the arquebus autorecognized in the previous version of the module, now it is not. I will try to make a custom animation for sure, just wondering what happened.

**Comment by Maelorn09** [comment]
@MrVauxs I don't know why, but even the autorecognized animations doesn't play. Here's the console error
![image](https://user-images.githubusercontent.com/114569560/197174151-7f6a643f-cda4-41c3-9461-cb1571de6a89.png)

**Comment by MrVauxs** [comment]
Update to 4.0.13 to fix the issue. Now, I will still need your Autorecognition Menu file to see what is the issue with the broken update menu.

**Comment by MrVauxs** [comment]
Closing unless something comes up.
