### ISSUE TITLE
Is Dimension Door broken ?

### ISSUE THREAD

**Issue by Far2Casual** [MrVauxs/pf2e-jb2a-macros#41]
When I click on the space I want to teleport the token to, nothing happens. I have some errors/warnings popping in the console:

Error: You are accessing PlaceableObject#data which is no longer used and instead the Document class should be referenced directly as PlaceableObject#document.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:1692:19)
    at TokenPF2e.get (foundry.js:24731:23)
    at eval (eval at executeScript (Macros.js:44:15), <anonymous>:79:68)
    at async Macro.executeMacro (Macros.js:239:12)
    at async Proxy.<anonymous> (sequencer.js:108:13)
    at async Proxy.run (func.js:18:9)
    at async Proxy._execute (func.js:26:9)
    at async Proxy.play (sequencer.js:38:31)

**Comment by MrVauxs** [comment]
Works for me. Will need more info.

**Comment by Far2Casual** [comment]
Okay I have it. It won't work because in some cases, the name of the spell is Dimensional Door (At will). In that case, the test on the name here won't find it: `switch (args[0].item.name.replace(/\(.+\)/, "").trim())`

**Comment by MrVauxs** [comment]
It should find it given it removes the `(At will)` part

**Comment by Far2Casual** [comment]
You're right, the problem is lower in fact, when it builds the Sequencer effet (line 94 on me):
`switch (args[0].item.name) {`
should be replaced by:
`switch (args[0].item.name.replace(/\(.+\)/, "").trim()) {`

**Comment by MrVauxs** [comment]
Releasing that in a quick fix
