### ISSUE TITLE
Dimension Jumps with localization

### ISSUE THREAD

**Issue by Far2Casual** [MrVauxs/pf2e-jb2a-macros#44]
The current implementation on the Dimension Jumps macro tests items on the name which will usually get messed up by translation/localization. For example in French, Dimension Door will become `"Porte dimensionnelle (Dimension Door) (A volonté)"`, and the macro will fail.

I think the best way to do it is to test on `item.system.slug`, which the localizations usually won't alter. So replacing this:
`switch (args[0].item.name.replace(/\(.+\)/, "").trim()) {
    case "Dimensional Assault":`
by this:
`switch (args[0].item.system.slug) {
    case "dimensional-assault"`

will work even if the name is translated, and even in the annoying "At will" or "Constant" cases (the slug doesn't change).

Maybe an even better way to do it would maybe be to test for the sourceId directly, so:
`switch (args[0].item.flags.core.sourceId) {
    case "Compendium.pf2e.spells-srd.5p9Y4ACrtRM4gTpN":`

I've tested both locally and they both work.

**Comment by MrVauxs** [comment]
Implemented in 2.5.2

**Comment by Far2Casual** [comment]
Thanks a lot ! 🙏
