### ISSUE TITLE
the world

### ISSUE THREAD

**Issue by ExileofBrokenSky** [MrVauxs/pf2e-jb2a-macros#47]
Used find the culprit to narrow this strange error to this mod. 
Whenever I update pretty much any item in any way an error notification pops up saying simply 'the world' and this error in the console
![image](https://user-images.githubusercontent.com/28786777/199064201-fb960144-6504-4d20-a4a2-91c5d646ce71.png)

**Comment by MrVauxs** [comment]
You have "Use Local Macros" setting enabled. Disable it.
The error itself is a buggy message saying it can't find the Equipment Changes macro. Fixed in the next update.
