### ISSUE TITLE
Bardic Cantripry macro has problem with localized game 

### ISSUE THREAD

**Issue by AlphaStarguide** [MrVauxs/pf2e-jb2a-macros#48]
Thank you for your amazing work.
I'm hosting a localized game with Babele and I found that Bardic Cantripry doesn't work.
I had a look at the code and saw it depends on the Spell effect name which in my case was localized.
![image](https://user-images.githubusercontent.com/90250769/199161674-4740e14a-295e-4a3f-9b1e-ab71d6df93ed.png)
Suggesting change the key from spellname to SourceID so it won't be influenced by localization.
Thank you.

**Comment by AlphaStarguide** [comment]
And I noticed other marco also using the item name(like Aeon Stone macro use item name to judge the stone type) rather than SourceID.
I know it would take some time but could you possibly let them use SourceID so there would be no more localization issue?

**Comment by MrVauxs** [comment]
Replaced both with slugs that I believe are not translated in version 2.5.3
