### ISSUE TITLE
Rage's Particles Animation is Patreon-only

### ISSUE THREAD

**Issue by MemelyPepeartly** [MrVauxs/pf2e-jb2a-macros#5]
Back again with another QA style issue to bring to ones attention: This episode - The rage macro

All the others function proper as far as I can tell, but the rage one fails to do the really cool rage thing. By the looks due to just pointing to the wrong place? All dependencies are enabled as far as I am aware
![image](https://user-images.githubusercontent.com/58655781/174673409-ad6a8187-c3c9-4243-9dbe-7494ba66e256.png)

**Comment by MrVauxs** [comment]
Nope, it's all working. What the issue probably is, is that you're on the free version of the JB2A assets module.
The free version only includes the `greenyellow` particles.

I'll leave the issue open, but I will note that repurposing the module to fit the free version is not a priority.

**Comment by MrVauxs** [comment]
Fixed in 1.7.5
