### ISSUE TITLE
Feature request: import only selected

### ISSUE THREAD

**Issue by LeandroMartinelli** [MrVauxs/pf2e-jb2a-macros#69]
While import the new autorec, can we have a list (checkbox) with animations to import and animations to not import?

If for example, I don't want to import the "persistent damage X" a can just leave it unchecked this way people don't have to delete it after every update!

And thanks for the work!!

**Comment by MrVauxs** [comment]
It's very unlikely I will implement this as it would require a significant overhaul of how the update menu works, or would just be a janky solution (you'd still have to select everything you don't want get updated every time you update, or I save that somewhere in a separate menu). There are also other solutions to the problem, as stated below:

I recommend simply changing the animation to an empty custom file. That will:
1. Make the animation no longer appear as it will just try to grab an empty image, fail, and quietly do nothing as if it never existed.
2. Make PF2e Animations treat it as a custom animation and thus, not update it back to being visible.

**Comment by LeandroMartinelli** [comment]
Thanks for the answer! Change the animations probably will do!
Keep up the great work!

**Comment by Far2Casual** [comment]
@MrVauxs  Something along the lines but specifically for transforms: if you don't have the bestiary token pack installed, then we have an error everytime a transformation happens because the token image doesn't exist. Maybe just a setting (deactivated by default ?) to prevent those animation to run if the token pack is not installed ?

**Comment by MrVauxs** [comment]
It should have been just quietly not finding the images and ignoring everything. Will check and fix it there's an issue.

**Comment by MrVauxs** [comment]
> @MrVauxs Something along the lines but specifically for transforms: if you don't have the bestiary token pack installed, then we have an error everytime a transformation happens because the token image doesn't exist. Maybe just a setting (deactivated by default ?) to prevent those animation to run if the token pack is not installed ?

Fixed for the next update.

**Comment by MrVauxs** [comment]
Added this in 2.7.4.
