### ISSUE TITLE
Some of the animations don't work

### ISSUE THREAD

**Issue by ca3du5** [MrVauxs/pf2e-jb2a-macros#7]
Hello,

Not a huge deal, very pleased with this compendium overall and thank you for putting it together!

The only issue I am having with it is that sequencer can't seem to find some of the files it needs for the animations. Half the ones I have tried work, but healing for instance, doesn't work. Sequencer comes up with an error saying it cannot find the file. 

Any help you could give would be appreciated.

**Comment by MrVauxs** [comment]
Would appreciate concrete examples of the files missing.
Note that this compendium was made with the Patreon version of JB2A in mind, but should work with free version most of the time.
