### ISSUE TITLE
Quickened and Invisible conditions throw errors

### ISSUE THREAD

**Issue by ILikeCoolThings** [MrVauxs/pf2e-jb2a-macros#72]
When you add the Quickened and Invisible condition to a token, the below error is displayed.
Let me know if you need more info.

![image](https://user-images.githubusercontent.com/54457140/208217612-2d76e774-f867-45c5-9d61-011e940c74d3.png)

**Comment by MrVauxs** [comment]
Your animations are woefully outdated. Use the Update Menu to update them.
If the menu says it cannot, follow it's instructions to delete the animations and run the update menu again.

**Comment by ILikeCoolThings** [comment]
Was on the newest version... but had to manually overwrite.
Thanks for the quick help.
