### ISSUE TITLE
Error Message when applying Inspire Courage

### ISSUE THREAD

**Issue by jmgoldb** [MrVauxs/pf2e-jb2a-macros#8]
Hello, I just installed this module, and tested it out with the rage effect, which looks fantastic.

I then noticed however that whenever I (as a GM or as a player) apply the Inspire Courage effect to a token, that, while it does apply correctly, I also get a big error message that says `FURNACE.MACROS.MacroSyntaxError`

I currently do have the Patreon version of JB2A, and the error doesn't appear with pf2e-jb2a-macros (and its dependencies) disabled.

If it at all helps, here is a copypaste of the Inspire Courage effect macro as I have it:

```
const actors = canvas.tokens.controlled.flatMap((token) => token.actor ?? []);
if (actors.length === 0 && game.user.character) actors.push(game.user.character);
if (actors.length === 0) {
    const message = game.i18n.localize("PF2E.ErrorMessage.NoTokenSelected");
    return ui.notifications.error(message);
}

const ITEM_UUID = "Compendium.pf2e.spell-effects.beReeFroAx24hj83"; // Spell Effect: Inspire Courage
const source = (await fromUuid(ITEM_UUID)).toObject();
source.flags = mergeObject(source.flags ?? {}, { core: { sourceId: ITEM_UUID } });

for (const actor of actors) {
    const existing = actor.itemTypes.effect.find((e) => e.data.flags.core?.sourceId === ITEM_UUID);
    if (existing) {
        await existing.delete();
    } else {
        await actor.createEmbeddedDocuments("Item", [source]);
    }
}
```

**Comment by MrVauxs** [comment]
That is... not my macro.

**Comment by MrVauxs** [comment]
Resolved on Discord.
