### ISSUE TITLE
Grim Tendrils Spells issue

### ISSUE THREAD

**Issue by ShadowsGamer** [MrVauxs/pf2e-jb2a-macros#84]
When casting Grim Tendrils spells it throws errors in console.

- Sequencer | Module: PF2e Animations | Effect | atLocation - could not find position of given object
- advanced-macros | There was an error in your macro syntax. See the console (F12) for details : Error: Sequencer | Module: PF2e Animations | Effect | atLocation - could not find position of given object
- advanced-macros | TypeError: wrapped is not a function
Reproducible with only animation module active.

**Comment by RednalPR** [comment]
![image](https://user-images.githubusercontent.com/121951961/210568420-74e4175c-5765-4919-8c51-2fdf18d89fe3.png)
